from roster import Roster

from vehicles import (amblecote, beerwoods, bottlebrook, brass_monkey, brigand, brightling,
                      broadrock, buildwas, buff, coalhall, cloud_hill, coldfall, crime_rigg,
                      easywheal, fairlop, foreshore, fortiscue, foxley, goldmire, gravelhead,
                      greenscoe, griff, honister, jinglepot, knockdown, ladycross, leyburn,
                      limebreach, littleduke, mcdowell, meriden, merrivale, moota,
                      nettlebridge, newbold, oylbarral, pigstick, powerstock, quickset,
                      reaver, ribble, road_thief, shotover, silvertop, sparkford, speedwell,
                      stancliffe, steeraway, stungun, swineshead, tallyho, thunder,
                      thurlbear, topley, trefell, twinhills, waterperry, witch_hill, wookey)

roster = Roster(id = 'brit',
                title = 'Brit',
                truck_speeds = {0: 20, 1900: 25, 1920: 40, 1940: 55, 1960: 70, 1980: 80},
                tram_speeds = {0: 20, 1895: 35, 1940: 50, 1980: 65},
                buy_menu_sort_order = ['ladycross',
                                       'fairlop',
                                       'leyburn',
                                       'newbold',
                                       'thunder',
                                       'moota',
                                       'topley',
                                       'twinhills',
                                       'foxley',
                                       'tallyho',
                                       'brass_monkey',
                                       'goldmire',
                                       'littleduke',
                                       'amblecote',
                                       'brightling',
                                       'jinglepot',
                                       'easywheal',
                                       'quickset',
                                       'speedwell',
                                       'buildwas',
                                       'coalhall',
                                       'gravelhead',
                                       'broadrock',
                                       'witch_hill',
                                       'oylbarral',
                                       'greenscoe',
                                       'meriden',
                                       'cloud_hill',
                                       'griff',
                                       'trefell',
                                       'knockdown',
                                       'buff',
                                       'nettlebridge',
                                       'honister',
                                       'wookey',
                                       'powerstock',
                                       'thurlbear',
                                       'limebreach',
                                       'ribble',
                                       'mcdowell',
                                       'shotover',
                                       'pigstick',
                                       'swineshead',
                                       'stungun',
                                       'bottlebrook',
                                       'beerwoods',
                                       'waterperry',
                                       'silvertop',
                                       'merrivale',
                                       'sparkford',
                                       'fortiscue',
                                       'coldfall',
                                       'foreshore',
                                       'stancliffe',
                                       'steeraway',
                                       'reaver',
                                       'crime_rigg',
                                       'brigand',
                                       'road_thief'])
